#!/usr/bin/env python3
import rospy, roslaunch
from herobot.msg import String
from std_msgs.msg import UInt8



def x():
	rospy.init_node('x', anonymous=True)
	height = input("height : ")
	c1, t1 = input("top : ").split(' ')
	c2, t2 = input("bottom : ").split(' ')
	height = float(height)
	pub_infor = rospy.Publisher('chatter', String, queue_size=20) 
	msg_infor = String()
	msg_infor.height = height
	msg_infor.color1 = c1
	msg_infor.type1 = t1
	msg_infor.color2 = c2
	msg_infor.type2 = t2
	while not rospy.is_shutdown():
		pub_infor.publish(msg_infor)
	
if __name__ == '__main__':
	try:
		x()
	except rospy.ROSInterruptException:
		pass
